/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SaasRouteImport } from "./routes/_saas"
import { Route as MarketingRouteImport } from "./routes/_marketing"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as SplatRouteImport } from "./routes/$"
import { Route as MarketingIndexRouteImport } from "./routes/_marketing/index"
import { Route as ImageProxySplatRouteImport } from "./routes/image-proxy/$"
import { Route as ApiHealthRouteImport } from "./routes/api/health"
import { Route as ApiSplatRouteImport } from "./routes/api/$"
import { Route as SaasOnboardingRouteImport } from "./routes/_saas/onboarding"
import { Route as SaasNewOrganizationRouteImport } from "./routes/_saas/new-organization"
import { Route as SaasChoosePlanRouteImport } from "./routes/_saas/choose-plan"
import { Route as SaasAppRouteImport } from "./routes/_saas/app"
import { Route as MarketingContactRouteImport } from "./routes/_marketing/contact"
import { Route as MarketingChangelogRouteImport } from "./routes/_marketing/changelog"
import { Route as AuthVerifyRouteImport } from "./routes/_auth/verify"
import { Route as AuthSignupRouteImport } from "./routes/_auth/signup"
import { Route as AuthResetPasswordRouteImport } from "./routes/_auth/reset-password"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as AuthForgotPasswordRouteImport } from "./routes/_auth/forgot-password"
import { Route as MarketingBlogIndexRouteImport } from "./routes/_marketing/blog/index"
import { Route as SaasOrganizationInvitationInvitationIdRouteImport } from "./routes/_saas/organization-invitation/$invitationId"
import { Route as SaasAppAccountRouteImport } from "./routes/_saas/app/_account"
import { Route as MarketingLegalSplatRouteImport } from "./routes/_marketing/legal/$"
import { Route as MarketingDocsSplatRouteImport } from "./routes/_marketing/docs/$"
import { Route as MarketingBlogSplatRouteImport } from "./routes/_marketing/blog/$"
import { Route as SaasAppAccountIndexRouteImport } from "./routes/_saas/app/_account/index"
import { Route as SaasAppOrgOrganizationSlugRouteImport } from "./routes/_saas/app/_org/$organizationSlug"
import { Route as SaasAppFullbleedOrganizationSlugRouteImport } from "./routes/_saas/app/_fullbleed/$organizationSlug"
import { Route as SaasAppAccountSettingsRouteImport } from "./routes/_saas/app/_account/settings"
import { Route as SaasAppAccountAdminRouteImport } from "./routes/_saas/app/_account/admin"
import { Route as SaasAppOrgOrganizationSlugIndexRouteImport } from "./routes/_saas/app/_org/$organizationSlug/index"
import { Route as SaasAppAccountSettingsIndexRouteImport } from "./routes/_saas/app/_account/settings/index"
import { Route as SaasAppAccountAdminIndexRouteImport } from "./routes/_saas/app/_account/admin/index"
import { Route as SaasAppOrgOrganizationSlugSettingsRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings"
import { Route as SaasAppAccountSettingsSecurityRouteImport } from "./routes/_saas/app/_account/settings/security"
import { Route as SaasAppAccountSettingsPrivacyRouteImport } from "./routes/_saas/app/_account/settings/privacy"
import { Route as SaasAppAccountSettingsNotificationsRouteImport } from "./routes/_saas/app/_account/settings/notifications"
import { Route as SaasAppAccountSettingsGeneralRouteImport } from "./routes/_saas/app/_account/settings/general"
import { Route as SaasAppAccountSettingsDangerZoneRouteImport } from "./routes/_saas/app/_account/settings/danger-zone"
import { Route as SaasAppAccountAdminUsersRouteImport } from "./routes/_saas/app/_account/admin/users"
import { Route as SaasAppAccountAdminFeatureFlagsRouteImport } from "./routes/_saas/app/_account/admin/feature-flags"
import { Route as SaasAppOrgOrganizationSlugSettingsIndexRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/index"
import { Route as SaasAppAccountAdminOrganizationsIndexRouteImport } from "./routes/_saas/app/_account/admin/organizations/index"
import { Route as SaasAppOrgOrganizationSlugSettingsWebhooksRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/webhooks"
import { Route as SaasAppOrgOrganizationSlugSettingsRolesRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/roles"
import { Route as SaasAppOrgOrganizationSlugSettingsMembersRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/members"
import { Route as SaasAppOrgOrganizationSlugSettingsIntegrationsRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/integrations"
import { Route as SaasAppOrgOrganizationSlugSettingsGeneralRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/general"
import { Route as SaasAppOrgOrganizationSlugSettingsDangerZoneRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/danger-zone"
import { Route as SaasAppOrgOrganizationSlugSettingsBillingRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/billing"
import { Route as SaasAppOrgOrganizationSlugSettingsAuditRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/audit"
import { Route as SaasAppOrgOrganizationSlugSettingsApiKeysRouteImport } from "./routes/_saas/app/_org/$organizationSlug/settings/api-keys"
import { Route as SaasAppAccountAdminOrganizationsIdRouteImport } from "./routes/_saas/app/_account/admin/organizations/$id"

const SaasRoute = SaasRouteImport.update({
  id: "/_saas",
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: "/_marketing",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MarketingRoute,
} as any)
const ImageProxySplatRoute = ImageProxySplatRouteImport.update({
  id: "/image-proxy/$",
  path: "/image-proxy/$",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => rootRouteImport,
} as any)
const SaasOnboardingRoute = SaasOnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => SaasRoute,
} as any)
const SaasNewOrganizationRoute = SaasNewOrganizationRouteImport.update({
  id: "/new-organization",
  path: "/new-organization",
  getParentRoute: () => SaasRoute,
} as any)
const SaasChoosePlanRoute = SaasChoosePlanRouteImport.update({
  id: "/choose-plan",
  path: "/choose-plan",
  getParentRoute: () => SaasRoute,
} as any)
const SaasAppRoute = SaasAppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => SaasRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingChangelogRoute = MarketingChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => MarketingRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: "/verify",
  path: "/verify",
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRoute,
} as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => MarketingRoute,
} as any)
const SaasOrganizationInvitationInvitationIdRoute =
  SaasOrganizationInvitationInvitationIdRouteImport.update({
    id: "/organization-invitation/$invitationId",
    path: "/organization-invitation/$invitationId",
    getParentRoute: () => SaasRoute,
  } as any)
const SaasAppAccountRoute = SaasAppAccountRouteImport.update({
  id: "/_account",
  getParentRoute: () => SaasAppRoute,
} as any)
const MarketingLegalSplatRoute = MarketingLegalSplatRouteImport.update({
  id: "/legal/$",
  path: "/legal/$",
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDocsSplatRoute = MarketingDocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogSplatRoute = MarketingBlogSplatRouteImport.update({
  id: "/blog/$",
  path: "/blog/$",
  getParentRoute: () => MarketingRoute,
} as any)
const SaasAppAccountIndexRoute = SaasAppAccountIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SaasAppAccountRoute,
} as any)
const SaasAppOrgOrganizationSlugRoute =
  SaasAppOrgOrganizationSlugRouteImport.update({
    id: "/_org/$organizationSlug",
    path: "/$organizationSlug",
    getParentRoute: () => SaasAppRoute,
  } as any)
const SaasAppFullbleedOrganizationSlugRoute =
  SaasAppFullbleedOrganizationSlugRouteImport.update({
    id: "/_fullbleed/$organizationSlug",
    path: "/$organizationSlug",
    getParentRoute: () => SaasAppRoute,
  } as any)
const SaasAppAccountSettingsRoute = SaasAppAccountSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => SaasAppAccountRoute,
} as any)
const SaasAppAccountAdminRoute = SaasAppAccountAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => SaasAppAccountRoute,
} as any)
const SaasAppOrgOrganizationSlugIndexRoute =
  SaasAppOrgOrganizationSlugIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => SaasAppOrgOrganizationSlugRoute,
  } as any)
const SaasAppAccountSettingsIndexRoute =
  SaasAppAccountSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => SaasAppAccountSettingsRoute,
  } as any)
const SaasAppAccountAdminIndexRoute =
  SaasAppAccountAdminIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => SaasAppAccountAdminRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsRoute =
  SaasAppOrgOrganizationSlugSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => SaasAppOrgOrganizationSlugRoute,
  } as any)
const SaasAppAccountSettingsSecurityRoute =
  SaasAppAccountSettingsSecurityRouteImport.update({
    id: "/security",
    path: "/security",
    getParentRoute: () => SaasAppAccountSettingsRoute,
  } as any)
const SaasAppAccountSettingsPrivacyRoute =
  SaasAppAccountSettingsPrivacyRouteImport.update({
    id: "/privacy",
    path: "/privacy",
    getParentRoute: () => SaasAppAccountSettingsRoute,
  } as any)
const SaasAppAccountSettingsNotificationsRoute =
  SaasAppAccountSettingsNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => SaasAppAccountSettingsRoute,
  } as any)
const SaasAppAccountSettingsGeneralRoute =
  SaasAppAccountSettingsGeneralRouteImport.update({
    id: "/general",
    path: "/general",
    getParentRoute: () => SaasAppAccountSettingsRoute,
  } as any)
const SaasAppAccountSettingsDangerZoneRoute =
  SaasAppAccountSettingsDangerZoneRouteImport.update({
    id: "/danger-zone",
    path: "/danger-zone",
    getParentRoute: () => SaasAppAccountSettingsRoute,
  } as any)
const SaasAppAccountAdminUsersRoute =
  SaasAppAccountAdminUsersRouteImport.update({
    id: "/users",
    path: "/users",
    getParentRoute: () => SaasAppAccountAdminRoute,
  } as any)
const SaasAppAccountAdminFeatureFlagsRoute =
  SaasAppAccountAdminFeatureFlagsRouteImport.update({
    id: "/feature-flags",
    path: "/feature-flags",
    getParentRoute: () => SaasAppAccountAdminRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsIndexRoute =
  SaasAppOrgOrganizationSlugSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppAccountAdminOrganizationsIndexRoute =
  SaasAppAccountAdminOrganizationsIndexRouteImport.update({
    id: "/organizations/",
    path: "/organizations/",
    getParentRoute: () => SaasAppAccountAdminRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsWebhooksRoute =
  SaasAppOrgOrganizationSlugSettingsWebhooksRouteImport.update({
    id: "/webhooks",
    path: "/webhooks",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsRolesRoute =
  SaasAppOrgOrganizationSlugSettingsRolesRouteImport.update({
    id: "/roles",
    path: "/roles",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsMembersRoute =
  SaasAppOrgOrganizationSlugSettingsMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsIntegrationsRoute =
  SaasAppOrgOrganizationSlugSettingsIntegrationsRouteImport.update({
    id: "/integrations",
    path: "/integrations",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsGeneralRoute =
  SaasAppOrgOrganizationSlugSettingsGeneralRouteImport.update({
    id: "/general",
    path: "/general",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsDangerZoneRoute =
  SaasAppOrgOrganizationSlugSettingsDangerZoneRouteImport.update({
    id: "/danger-zone",
    path: "/danger-zone",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsBillingRoute =
  SaasAppOrgOrganizationSlugSettingsBillingRouteImport.update({
    id: "/billing",
    path: "/billing",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsAuditRoute =
  SaasAppOrgOrganizationSlugSettingsAuditRouteImport.update({
    id: "/audit",
    path: "/audit",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppOrgOrganizationSlugSettingsApiKeysRoute =
  SaasAppOrgOrganizationSlugSettingsApiKeysRouteImport.update({
    id: "/api-keys",
    path: "/api-keys",
    getParentRoute: () => SaasAppOrgOrganizationSlugSettingsRoute,
  } as any)
const SaasAppAccountAdminOrganizationsIdRoute =
  SaasAppAccountAdminOrganizationsIdRouteImport.update({
    id: "/organizations/$id",
    path: "/organizations/$id",
    getParentRoute: () => SaasAppAccountAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/$": typeof SplatRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/signup": typeof AuthSignupRoute
  "/verify": typeof AuthVerifyRoute
  "/changelog": typeof MarketingChangelogRoute
  "/contact": typeof MarketingContactRoute
  "/app": typeof SaasAppAccountRouteWithChildren
  "/choose-plan": typeof SaasChoosePlanRoute
  "/new-organization": typeof SaasNewOrganizationRoute
  "/onboarding": typeof SaasOnboardingRoute
  "/api/$": typeof ApiSplatRoute
  "/api/health": typeof ApiHealthRoute
  "/image-proxy/$": typeof ImageProxySplatRoute
  "/": typeof MarketingIndexRoute
  "/blog/$": typeof MarketingBlogSplatRoute
  "/docs/$": typeof MarketingDocsSplatRoute
  "/legal/$": typeof MarketingLegalSplatRoute
  "/organization-invitation/$invitationId": typeof SaasOrganizationInvitationInvitationIdRoute
  "/blog": typeof MarketingBlogIndexRoute
  "/app/admin": typeof SaasAppAccountAdminRouteWithChildren
  "/app/settings": typeof SaasAppAccountSettingsRouteWithChildren
  "/app/$organizationSlug": typeof SaasAppOrgOrganizationSlugRouteWithChildren
  "/app/": typeof SaasAppAccountIndexRoute
  "/app/admin/feature-flags": typeof SaasAppAccountAdminFeatureFlagsRoute
  "/app/admin/users": typeof SaasAppAccountAdminUsersRoute
  "/app/settings/danger-zone": typeof SaasAppAccountSettingsDangerZoneRoute
  "/app/settings/general": typeof SaasAppAccountSettingsGeneralRoute
  "/app/settings/notifications": typeof SaasAppAccountSettingsNotificationsRoute
  "/app/settings/privacy": typeof SaasAppAccountSettingsPrivacyRoute
  "/app/settings/security": typeof SaasAppAccountSettingsSecurityRoute
  "/app/$organizationSlug/settings": typeof SaasAppOrgOrganizationSlugSettingsRouteWithChildren
  "/app/admin/": typeof SaasAppAccountAdminIndexRoute
  "/app/settings/": typeof SaasAppAccountSettingsIndexRoute
  "/app/$organizationSlug/": typeof SaasAppOrgOrganizationSlugIndexRoute
  "/app/admin/organizations/$id": typeof SaasAppAccountAdminOrganizationsIdRoute
  "/app/$organizationSlug/settings/api-keys": typeof SaasAppOrgOrganizationSlugSettingsApiKeysRoute
  "/app/$organizationSlug/settings/audit": typeof SaasAppOrgOrganizationSlugSettingsAuditRoute
  "/app/$organizationSlug/settings/billing": typeof SaasAppOrgOrganizationSlugSettingsBillingRoute
  "/app/$organizationSlug/settings/danger-zone": typeof SaasAppOrgOrganizationSlugSettingsDangerZoneRoute
  "/app/$organizationSlug/settings/general": typeof SaasAppOrgOrganizationSlugSettingsGeneralRoute
  "/app/$organizationSlug/settings/integrations": typeof SaasAppOrgOrganizationSlugSettingsIntegrationsRoute
  "/app/$organizationSlug/settings/members": typeof SaasAppOrgOrganizationSlugSettingsMembersRoute
  "/app/$organizationSlug/settings/roles": typeof SaasAppOrgOrganizationSlugSettingsRolesRoute
  "/app/$organizationSlug/settings/webhooks": typeof SaasAppOrgOrganizationSlugSettingsWebhooksRoute
  "/app/admin/organizations": typeof SaasAppAccountAdminOrganizationsIndexRoute
  "/app/$organizationSlug/settings/": typeof SaasAppOrgOrganizationSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  "/$": typeof SplatRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/signup": typeof AuthSignupRoute
  "/verify": typeof AuthVerifyRoute
  "/changelog": typeof MarketingChangelogRoute
  "/contact": typeof MarketingContactRoute
  "/app": typeof SaasAppAccountIndexRoute
  "/choose-plan": typeof SaasChoosePlanRoute
  "/new-organization": typeof SaasNewOrganizationRoute
  "/onboarding": typeof SaasOnboardingRoute
  "/api/$": typeof ApiSplatRoute
  "/api/health": typeof ApiHealthRoute
  "/image-proxy/$": typeof ImageProxySplatRoute
  "/": typeof MarketingIndexRoute
  "/blog/$": typeof MarketingBlogSplatRoute
  "/docs/$": typeof MarketingDocsSplatRoute
  "/legal/$": typeof MarketingLegalSplatRoute
  "/organization-invitation/$invitationId": typeof SaasOrganizationInvitationInvitationIdRoute
  "/blog": typeof MarketingBlogIndexRoute
  "/app/$organizationSlug": typeof SaasAppOrgOrganizationSlugIndexRoute
  "/app/admin/feature-flags": typeof SaasAppAccountAdminFeatureFlagsRoute
  "/app/admin/users": typeof SaasAppAccountAdminUsersRoute
  "/app/settings/danger-zone": typeof SaasAppAccountSettingsDangerZoneRoute
  "/app/settings/general": typeof SaasAppAccountSettingsGeneralRoute
  "/app/settings/notifications": typeof SaasAppAccountSettingsNotificationsRoute
  "/app/settings/privacy": typeof SaasAppAccountSettingsPrivacyRoute
  "/app/settings/security": typeof SaasAppAccountSettingsSecurityRoute
  "/app/admin": typeof SaasAppAccountAdminIndexRoute
  "/app/settings": typeof SaasAppAccountSettingsIndexRoute
  "/app/admin/organizations/$id": typeof SaasAppAccountAdminOrganizationsIdRoute
  "/app/$organizationSlug/settings/api-keys": typeof SaasAppOrgOrganizationSlugSettingsApiKeysRoute
  "/app/$organizationSlug/settings/audit": typeof SaasAppOrgOrganizationSlugSettingsAuditRoute
  "/app/$organizationSlug/settings/billing": typeof SaasAppOrgOrganizationSlugSettingsBillingRoute
  "/app/$organizationSlug/settings/danger-zone": typeof SaasAppOrgOrganizationSlugSettingsDangerZoneRoute
  "/app/$organizationSlug/settings/general": typeof SaasAppOrgOrganizationSlugSettingsGeneralRoute
  "/app/$organizationSlug/settings/integrations": typeof SaasAppOrgOrganizationSlugSettingsIntegrationsRoute
  "/app/$organizationSlug/settings/members": typeof SaasAppOrgOrganizationSlugSettingsMembersRoute
  "/app/$organizationSlug/settings/roles": typeof SaasAppOrgOrganizationSlugSettingsRolesRoute
  "/app/$organizationSlug/settings/webhooks": typeof SaasAppOrgOrganizationSlugSettingsWebhooksRoute
  "/app/admin/organizations": typeof SaasAppAccountAdminOrganizationsIndexRoute
  "/app/$organizationSlug/settings": typeof SaasAppOrgOrganizationSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/$": typeof SplatRoute
  "/_auth": typeof AuthRouteWithChildren
  "/_marketing": typeof MarketingRouteWithChildren
  "/_saas": typeof SaasRouteWithChildren
  "/_auth/forgot-password": typeof AuthForgotPasswordRoute
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/reset-password": typeof AuthResetPasswordRoute
  "/_auth/signup": typeof AuthSignupRoute
  "/_auth/verify": typeof AuthVerifyRoute
  "/_marketing/changelog": typeof MarketingChangelogRoute
  "/_marketing/contact": typeof MarketingContactRoute
  "/_saas/app": typeof SaasAppRouteWithChildren
  "/_saas/choose-plan": typeof SaasChoosePlanRoute
  "/_saas/new-organization": typeof SaasNewOrganizationRoute
  "/_saas/onboarding": typeof SaasOnboardingRoute
  "/api/$": typeof ApiSplatRoute
  "/api/health": typeof ApiHealthRoute
  "/image-proxy/$": typeof ImageProxySplatRoute
  "/_marketing/": typeof MarketingIndexRoute
  "/_marketing/blog/$": typeof MarketingBlogSplatRoute
  "/_marketing/docs/$": typeof MarketingDocsSplatRoute
  "/_marketing/legal/$": typeof MarketingLegalSplatRoute
  "/_saas/app/_account": typeof SaasAppAccountRouteWithChildren
  "/_saas/organization-invitation/$invitationId": typeof SaasOrganizationInvitationInvitationIdRoute
  "/_marketing/blog/": typeof MarketingBlogIndexRoute
  "/_saas/app/_account/admin": typeof SaasAppAccountAdminRouteWithChildren
  "/_saas/app/_account/settings": typeof SaasAppAccountSettingsRouteWithChildren
  "/_saas/app/_fullbleed/$organizationSlug": typeof SaasAppFullbleedOrganizationSlugRoute
  "/_saas/app/_org/$organizationSlug": typeof SaasAppOrgOrganizationSlugRouteWithChildren
  "/_saas/app/_account/": typeof SaasAppAccountIndexRoute
  "/_saas/app/_account/admin/feature-flags": typeof SaasAppAccountAdminFeatureFlagsRoute
  "/_saas/app/_account/admin/users": typeof SaasAppAccountAdminUsersRoute
  "/_saas/app/_account/settings/danger-zone": typeof SaasAppAccountSettingsDangerZoneRoute
  "/_saas/app/_account/settings/general": typeof SaasAppAccountSettingsGeneralRoute
  "/_saas/app/_account/settings/notifications": typeof SaasAppAccountSettingsNotificationsRoute
  "/_saas/app/_account/settings/privacy": typeof SaasAppAccountSettingsPrivacyRoute
  "/_saas/app/_account/settings/security": typeof SaasAppAccountSettingsSecurityRoute
  "/_saas/app/_org/$organizationSlug/settings": typeof SaasAppOrgOrganizationSlugSettingsRouteWithChildren
  "/_saas/app/_account/admin/": typeof SaasAppAccountAdminIndexRoute
  "/_saas/app/_account/settings/": typeof SaasAppAccountSettingsIndexRoute
  "/_saas/app/_org/$organizationSlug/": typeof SaasAppOrgOrganizationSlugIndexRoute
  "/_saas/app/_account/admin/organizations/$id": typeof SaasAppAccountAdminOrganizationsIdRoute
  "/_saas/app/_org/$organizationSlug/settings/api-keys": typeof SaasAppOrgOrganizationSlugSettingsApiKeysRoute
  "/_saas/app/_org/$organizationSlug/settings/audit": typeof SaasAppOrgOrganizationSlugSettingsAuditRoute
  "/_saas/app/_org/$organizationSlug/settings/billing": typeof SaasAppOrgOrganizationSlugSettingsBillingRoute
  "/_saas/app/_org/$organizationSlug/settings/danger-zone": typeof SaasAppOrgOrganizationSlugSettingsDangerZoneRoute
  "/_saas/app/_org/$organizationSlug/settings/general": typeof SaasAppOrgOrganizationSlugSettingsGeneralRoute
  "/_saas/app/_org/$organizationSlug/settings/integrations": typeof SaasAppOrgOrganizationSlugSettingsIntegrationsRoute
  "/_saas/app/_org/$organizationSlug/settings/members": typeof SaasAppOrgOrganizationSlugSettingsMembersRoute
  "/_saas/app/_org/$organizationSlug/settings/roles": typeof SaasAppOrgOrganizationSlugSettingsRolesRoute
  "/_saas/app/_org/$organizationSlug/settings/webhooks": typeof SaasAppOrgOrganizationSlugSettingsWebhooksRoute
  "/_saas/app/_account/admin/organizations/": typeof SaasAppAccountAdminOrganizationsIndexRoute
  "/_saas/app/_org/$organizationSlug/settings/": typeof SaasAppOrgOrganizationSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/$"
    | "/forgot-password"
    | "/login"
    | "/reset-password"
    | "/signup"
    | "/verify"
    | "/changelog"
    | "/contact"
    | "/app"
    | "/choose-plan"
    | "/new-organization"
    | "/onboarding"
    | "/api/$"
    | "/api/health"
    | "/image-proxy/$"
    | "/"
    | "/blog/$"
    | "/docs/$"
    | "/legal/$"
    | "/organization-invitation/$invitationId"
    | "/blog"
    | "/app/admin"
    | "/app/settings"
    | "/app/$organizationSlug"
    | "/app/"
    | "/app/admin/feature-flags"
    | "/app/admin/users"
    | "/app/settings/danger-zone"
    | "/app/settings/general"
    | "/app/settings/notifications"
    | "/app/settings/privacy"
    | "/app/settings/security"
    | "/app/$organizationSlug/settings"
    | "/app/admin/"
    | "/app/settings/"
    | "/app/$organizationSlug/"
    | "/app/admin/organizations/$id"
    | "/app/$organizationSlug/settings/api-keys"
    | "/app/$organizationSlug/settings/audit"
    | "/app/$organizationSlug/settings/billing"
    | "/app/$organizationSlug/settings/danger-zone"
    | "/app/$organizationSlug/settings/general"
    | "/app/$organizationSlug/settings/integrations"
    | "/app/$organizationSlug/settings/members"
    | "/app/$organizationSlug/settings/roles"
    | "/app/$organizationSlug/settings/webhooks"
    | "/app/admin/organizations"
    | "/app/$organizationSlug/settings/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/$"
    | "/forgot-password"
    | "/login"
    | "/reset-password"
    | "/signup"
    | "/verify"
    | "/changelog"
    | "/contact"
    | "/app"
    | "/choose-plan"
    | "/new-organization"
    | "/onboarding"
    | "/api/$"
    | "/api/health"
    | "/image-proxy/$"
    | "/"
    | "/blog/$"
    | "/docs/$"
    | "/legal/$"
    | "/organization-invitation/$invitationId"
    | "/blog"
    | "/app/$organizationSlug"
    | "/app/admin/feature-flags"
    | "/app/admin/users"
    | "/app/settings/danger-zone"
    | "/app/settings/general"
    | "/app/settings/notifications"
    | "/app/settings/privacy"
    | "/app/settings/security"
    | "/app/admin"
    | "/app/settings"
    | "/app/admin/organizations/$id"
    | "/app/$organizationSlug/settings/api-keys"
    | "/app/$organizationSlug/settings/audit"
    | "/app/$organizationSlug/settings/billing"
    | "/app/$organizationSlug/settings/danger-zone"
    | "/app/$organizationSlug/settings/general"
    | "/app/$organizationSlug/settings/integrations"
    | "/app/$organizationSlug/settings/members"
    | "/app/$organizationSlug/settings/roles"
    | "/app/$organizationSlug/settings/webhooks"
    | "/app/admin/organizations"
    | "/app/$organizationSlug/settings"
  id:
    | "__root__"
    | "/$"
    | "/_auth"
    | "/_marketing"
    | "/_saas"
    | "/_auth/forgot-password"
    | "/_auth/login"
    | "/_auth/reset-password"
    | "/_auth/signup"
    | "/_auth/verify"
    | "/_marketing/changelog"
    | "/_marketing/contact"
    | "/_saas/app"
    | "/_saas/choose-plan"
    | "/_saas/new-organization"
    | "/_saas/onboarding"
    | "/api/$"
    | "/api/health"
    | "/image-proxy/$"
    | "/_marketing/"
    | "/_marketing/blog/$"
    | "/_marketing/docs/$"
    | "/_marketing/legal/$"
    | "/_saas/app/_account"
    | "/_saas/organization-invitation/$invitationId"
    | "/_marketing/blog/"
    | "/_saas/app/_account/admin"
    | "/_saas/app/_account/settings"
    | "/_saas/app/_fullbleed/$organizationSlug"
    | "/_saas/app/_org/$organizationSlug"
    | "/_saas/app/_account/"
    | "/_saas/app/_account/admin/feature-flags"
    | "/_saas/app/_account/admin/users"
    | "/_saas/app/_account/settings/danger-zone"
    | "/_saas/app/_account/settings/general"
    | "/_saas/app/_account/settings/notifications"
    | "/_saas/app/_account/settings/privacy"
    | "/_saas/app/_account/settings/security"
    | "/_saas/app/_org/$organizationSlug/settings"
    | "/_saas/app/_account/admin/"
    | "/_saas/app/_account/settings/"
    | "/_saas/app/_org/$organizationSlug/"
    | "/_saas/app/_account/admin/organizations/$id"
    | "/_saas/app/_org/$organizationSlug/settings/api-keys"
    | "/_saas/app/_org/$organizationSlug/settings/audit"
    | "/_saas/app/_org/$organizationSlug/settings/billing"
    | "/_saas/app/_org/$organizationSlug/settings/danger-zone"
    | "/_saas/app/_org/$organizationSlug/settings/general"
    | "/_saas/app/_org/$organizationSlug/settings/integrations"
    | "/_saas/app/_org/$organizationSlug/settings/members"
    | "/_saas/app/_org/$organizationSlug/settings/roles"
    | "/_saas/app/_org/$organizationSlug/settings/webhooks"
    | "/_saas/app/_account/admin/organizations/"
    | "/_saas/app/_org/$organizationSlug/settings/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  SaasRoute: typeof SaasRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ImageProxySplatRoute: typeof ImageProxySplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_saas": {
      id: "/_saas"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_marketing": {
      id: "/_marketing"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$": {
      id: "/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_marketing/": {
      id: "/_marketing/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/image-proxy/$": {
      id: "/image-proxy/$"
      path: "/image-proxy/$"
      fullPath: "/image-proxy/$"
      preLoaderRoute: typeof ImageProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/health": {
      id: "/api/health"
      path: "/api/health"
      fullPath: "/api/health"
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/$": {
      id: "/api/$"
      path: "/api/$"
      fullPath: "/api/$"
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_saas/onboarding": {
      id: "/_saas/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof SaasOnboardingRouteImport
      parentRoute: typeof SaasRoute
    }
    "/_saas/new-organization": {
      id: "/_saas/new-organization"
      path: "/new-organization"
      fullPath: "/new-organization"
      preLoaderRoute: typeof SaasNewOrganizationRouteImport
      parentRoute: typeof SaasRoute
    }
    "/_saas/choose-plan": {
      id: "/_saas/choose-plan"
      path: "/choose-plan"
      fullPath: "/choose-plan"
      preLoaderRoute: typeof SaasChoosePlanRouteImport
      parentRoute: typeof SaasRoute
    }
    "/_saas/app": {
      id: "/_saas/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof SaasAppRouteImport
      parentRoute: typeof SaasRoute
    }
    "/_marketing/contact": {
      id: "/_marketing/contact"
      path: "/contact"
      fullPath: "/contact"
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_marketing/changelog": {
      id: "/_marketing/changelog"
      path: "/changelog"
      fullPath: "/changelog"
      preLoaderRoute: typeof MarketingChangelogRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_auth/verify": {
      id: "/_auth/verify"
      path: "/verify"
      fullPath: "/verify"
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/signup": {
      id: "/_auth/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/reset-password": {
      id: "/_auth/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/forgot-password": {
      id: "/_auth/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_marketing/blog/": {
      id: "/_marketing/blog/"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_saas/organization-invitation/$invitationId": {
      id: "/_saas/organization-invitation/$invitationId"
      path: "/organization-invitation/$invitationId"
      fullPath: "/organization-invitation/$invitationId"
      preLoaderRoute: typeof SaasOrganizationInvitationInvitationIdRouteImport
      parentRoute: typeof SaasRoute
    }
    "/_saas/app/_account": {
      id: "/_saas/app/_account"
      path: ""
      fullPath: "/app"
      preLoaderRoute: typeof SaasAppAccountRouteImport
      parentRoute: typeof SaasAppRoute
    }
    "/_marketing/legal/$": {
      id: "/_marketing/legal/$"
      path: "/legal/$"
      fullPath: "/legal/$"
      preLoaderRoute: typeof MarketingLegalSplatRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_marketing/docs/$": {
      id: "/_marketing/docs/$"
      path: "/docs/$"
      fullPath: "/docs/$"
      preLoaderRoute: typeof MarketingDocsSplatRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_marketing/blog/$": {
      id: "/_marketing/blog/$"
      path: "/blog/$"
      fullPath: "/blog/$"
      preLoaderRoute: typeof MarketingBlogSplatRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_saas/app/_account/": {
      id: "/_saas/app/_account/"
      path: "/"
      fullPath: "/app/"
      preLoaderRoute: typeof SaasAppAccountIndexRouteImport
      parentRoute: typeof SaasAppAccountRoute
    }
    "/_saas/app/_org/$organizationSlug": {
      id: "/_saas/app/_org/$organizationSlug"
      path: "/$organizationSlug"
      fullPath: "/app/$organizationSlug"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugRouteImport
      parentRoute: typeof SaasAppRoute
    }
    "/_saas/app/_fullbleed/$organizationSlug": {
      id: "/_saas/app/_fullbleed/$organizationSlug"
      path: "/$organizationSlug"
      fullPath: "/app/$organizationSlug"
      preLoaderRoute: typeof SaasAppFullbleedOrganizationSlugRouteImport
      parentRoute: typeof SaasAppRoute
    }
    "/_saas/app/_account/settings": {
      id: "/_saas/app/_account/settings"
      path: "/settings"
      fullPath: "/app/settings"
      preLoaderRoute: typeof SaasAppAccountSettingsRouteImport
      parentRoute: typeof SaasAppAccountRoute
    }
    "/_saas/app/_account/admin": {
      id: "/_saas/app/_account/admin"
      path: "/admin"
      fullPath: "/app/admin"
      preLoaderRoute: typeof SaasAppAccountAdminRouteImport
      parentRoute: typeof SaasAppAccountRoute
    }
    "/_saas/app/_org/$organizationSlug/": {
      id: "/_saas/app/_org/$organizationSlug/"
      path: "/"
      fullPath: "/app/$organizationSlug/"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugIndexRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugRoute
    }
    "/_saas/app/_account/settings/": {
      id: "/_saas/app/_account/settings/"
      path: "/"
      fullPath: "/app/settings/"
      preLoaderRoute: typeof SaasAppAccountSettingsIndexRouteImport
      parentRoute: typeof SaasAppAccountSettingsRoute
    }
    "/_saas/app/_account/admin/": {
      id: "/_saas/app/_account/admin/"
      path: "/"
      fullPath: "/app/admin/"
      preLoaderRoute: typeof SaasAppAccountAdminIndexRouteImport
      parentRoute: typeof SaasAppAccountAdminRoute
    }
    "/_saas/app/_org/$organizationSlug/settings": {
      id: "/_saas/app/_org/$organizationSlug/settings"
      path: "/settings"
      fullPath: "/app/$organizationSlug/settings"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugRoute
    }
    "/_saas/app/_account/settings/security": {
      id: "/_saas/app/_account/settings/security"
      path: "/security"
      fullPath: "/app/settings/security"
      preLoaderRoute: typeof SaasAppAccountSettingsSecurityRouteImport
      parentRoute: typeof SaasAppAccountSettingsRoute
    }
    "/_saas/app/_account/settings/privacy": {
      id: "/_saas/app/_account/settings/privacy"
      path: "/privacy"
      fullPath: "/app/settings/privacy"
      preLoaderRoute: typeof SaasAppAccountSettingsPrivacyRouteImport
      parentRoute: typeof SaasAppAccountSettingsRoute
    }
    "/_saas/app/_account/settings/notifications": {
      id: "/_saas/app/_account/settings/notifications"
      path: "/notifications"
      fullPath: "/app/settings/notifications"
      preLoaderRoute: typeof SaasAppAccountSettingsNotificationsRouteImport
      parentRoute: typeof SaasAppAccountSettingsRoute
    }
    "/_saas/app/_account/settings/general": {
      id: "/_saas/app/_account/settings/general"
      path: "/general"
      fullPath: "/app/settings/general"
      preLoaderRoute: typeof SaasAppAccountSettingsGeneralRouteImport
      parentRoute: typeof SaasAppAccountSettingsRoute
    }
    "/_saas/app/_account/settings/danger-zone": {
      id: "/_saas/app/_account/settings/danger-zone"
      path: "/danger-zone"
      fullPath: "/app/settings/danger-zone"
      preLoaderRoute: typeof SaasAppAccountSettingsDangerZoneRouteImport
      parentRoute: typeof SaasAppAccountSettingsRoute
    }
    "/_saas/app/_account/admin/users": {
      id: "/_saas/app/_account/admin/users"
      path: "/users"
      fullPath: "/app/admin/users"
      preLoaderRoute: typeof SaasAppAccountAdminUsersRouteImport
      parentRoute: typeof SaasAppAccountAdminRoute
    }
    "/_saas/app/_account/admin/feature-flags": {
      id: "/_saas/app/_account/admin/feature-flags"
      path: "/feature-flags"
      fullPath: "/app/admin/feature-flags"
      preLoaderRoute: typeof SaasAppAccountAdminFeatureFlagsRouteImport
      parentRoute: typeof SaasAppAccountAdminRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/": {
      id: "/_saas/app/_org/$organizationSlug/settings/"
      path: "/"
      fullPath: "/app/$organizationSlug/settings/"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsIndexRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_account/admin/organizations/": {
      id: "/_saas/app/_account/admin/organizations/"
      path: "/organizations"
      fullPath: "/app/admin/organizations"
      preLoaderRoute: typeof SaasAppAccountAdminOrganizationsIndexRouteImport
      parentRoute: typeof SaasAppAccountAdminRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/webhooks": {
      id: "/_saas/app/_org/$organizationSlug/settings/webhooks"
      path: "/webhooks"
      fullPath: "/app/$organizationSlug/settings/webhooks"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsWebhooksRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/roles": {
      id: "/_saas/app/_org/$organizationSlug/settings/roles"
      path: "/roles"
      fullPath: "/app/$organizationSlug/settings/roles"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsRolesRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/members": {
      id: "/_saas/app/_org/$organizationSlug/settings/members"
      path: "/members"
      fullPath: "/app/$organizationSlug/settings/members"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsMembersRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/integrations": {
      id: "/_saas/app/_org/$organizationSlug/settings/integrations"
      path: "/integrations"
      fullPath: "/app/$organizationSlug/settings/integrations"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsIntegrationsRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/general": {
      id: "/_saas/app/_org/$organizationSlug/settings/general"
      path: "/general"
      fullPath: "/app/$organizationSlug/settings/general"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsGeneralRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/danger-zone": {
      id: "/_saas/app/_org/$organizationSlug/settings/danger-zone"
      path: "/danger-zone"
      fullPath: "/app/$organizationSlug/settings/danger-zone"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsDangerZoneRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/billing": {
      id: "/_saas/app/_org/$organizationSlug/settings/billing"
      path: "/billing"
      fullPath: "/app/$organizationSlug/settings/billing"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsBillingRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/audit": {
      id: "/_saas/app/_org/$organizationSlug/settings/audit"
      path: "/audit"
      fullPath: "/app/$organizationSlug/settings/audit"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsAuditRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_org/$organizationSlug/settings/api-keys": {
      id: "/_saas/app/_org/$organizationSlug/settings/api-keys"
      path: "/api-keys"
      fullPath: "/app/$organizationSlug/settings/api-keys"
      preLoaderRoute: typeof SaasAppOrgOrganizationSlugSettingsApiKeysRouteImport
      parentRoute: typeof SaasAppOrgOrganizationSlugSettingsRoute
    }
    "/_saas/app/_account/admin/organizations/$id": {
      id: "/_saas/app/_account/admin/organizations/$id"
      path: "/organizations/$id"
      fullPath: "/app/admin/organizations/$id"
      preLoaderRoute: typeof SaasAppAccountAdminOrganizationsIdRouteImport
      parentRoute: typeof SaasAppAccountAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingChangelogRoute: typeof MarketingChangelogRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingBlogSplatRoute: typeof MarketingBlogSplatRoute
  MarketingDocsSplatRoute: typeof MarketingDocsSplatRoute
  MarketingLegalSplatRoute: typeof MarketingLegalSplatRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingChangelogRoute: MarketingChangelogRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingBlogSplatRoute: MarketingBlogSplatRoute,
  MarketingDocsSplatRoute: MarketingDocsSplatRoute,
  MarketingLegalSplatRoute: MarketingLegalSplatRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface SaasAppAccountAdminRouteChildren {
  SaasAppAccountAdminFeatureFlagsRoute: typeof SaasAppAccountAdminFeatureFlagsRoute
  SaasAppAccountAdminUsersRoute: typeof SaasAppAccountAdminUsersRoute
  SaasAppAccountAdminIndexRoute: typeof SaasAppAccountAdminIndexRoute
  SaasAppAccountAdminOrganizationsIdRoute: typeof SaasAppAccountAdminOrganizationsIdRoute
  SaasAppAccountAdminOrganizationsIndexRoute: typeof SaasAppAccountAdminOrganizationsIndexRoute
}

const SaasAppAccountAdminRouteChildren: SaasAppAccountAdminRouteChildren = {
  SaasAppAccountAdminFeatureFlagsRoute: SaasAppAccountAdminFeatureFlagsRoute,
  SaasAppAccountAdminUsersRoute: SaasAppAccountAdminUsersRoute,
  SaasAppAccountAdminIndexRoute: SaasAppAccountAdminIndexRoute,
  SaasAppAccountAdminOrganizationsIdRoute:
    SaasAppAccountAdminOrganizationsIdRoute,
  SaasAppAccountAdminOrganizationsIndexRoute:
    SaasAppAccountAdminOrganizationsIndexRoute,
}

const SaasAppAccountAdminRouteWithChildren =
  SaasAppAccountAdminRoute._addFileChildren(SaasAppAccountAdminRouteChildren)

interface SaasAppAccountSettingsRouteChildren {
  SaasAppAccountSettingsDangerZoneRoute: typeof SaasAppAccountSettingsDangerZoneRoute
  SaasAppAccountSettingsGeneralRoute: typeof SaasAppAccountSettingsGeneralRoute
  SaasAppAccountSettingsNotificationsRoute: typeof SaasAppAccountSettingsNotificationsRoute
  SaasAppAccountSettingsPrivacyRoute: typeof SaasAppAccountSettingsPrivacyRoute
  SaasAppAccountSettingsSecurityRoute: typeof SaasAppAccountSettingsSecurityRoute
  SaasAppAccountSettingsIndexRoute: typeof SaasAppAccountSettingsIndexRoute
}

const SaasAppAccountSettingsRouteChildren: SaasAppAccountSettingsRouteChildren =
  {
    SaasAppAccountSettingsDangerZoneRoute:
      SaasAppAccountSettingsDangerZoneRoute,
    SaasAppAccountSettingsGeneralRoute: SaasAppAccountSettingsGeneralRoute,
    SaasAppAccountSettingsNotificationsRoute:
      SaasAppAccountSettingsNotificationsRoute,
    SaasAppAccountSettingsPrivacyRoute: SaasAppAccountSettingsPrivacyRoute,
    SaasAppAccountSettingsSecurityRoute: SaasAppAccountSettingsSecurityRoute,
    SaasAppAccountSettingsIndexRoute: SaasAppAccountSettingsIndexRoute,
  }

const SaasAppAccountSettingsRouteWithChildren =
  SaasAppAccountSettingsRoute._addFileChildren(
    SaasAppAccountSettingsRouteChildren,
  )

interface SaasAppAccountRouteChildren {
  SaasAppAccountAdminRoute: typeof SaasAppAccountAdminRouteWithChildren
  SaasAppAccountSettingsRoute: typeof SaasAppAccountSettingsRouteWithChildren
  SaasAppAccountIndexRoute: typeof SaasAppAccountIndexRoute
}

const SaasAppAccountRouteChildren: SaasAppAccountRouteChildren = {
  SaasAppAccountAdminRoute: SaasAppAccountAdminRouteWithChildren,
  SaasAppAccountSettingsRoute: SaasAppAccountSettingsRouteWithChildren,
  SaasAppAccountIndexRoute: SaasAppAccountIndexRoute,
}

const SaasAppAccountRouteWithChildren = SaasAppAccountRoute._addFileChildren(
  SaasAppAccountRouteChildren,
)

interface SaasAppOrgOrganizationSlugSettingsRouteChildren {
  SaasAppOrgOrganizationSlugSettingsApiKeysRoute: typeof SaasAppOrgOrganizationSlugSettingsApiKeysRoute
  SaasAppOrgOrganizationSlugSettingsAuditRoute: typeof SaasAppOrgOrganizationSlugSettingsAuditRoute
  SaasAppOrgOrganizationSlugSettingsBillingRoute: typeof SaasAppOrgOrganizationSlugSettingsBillingRoute
  SaasAppOrgOrganizationSlugSettingsDangerZoneRoute: typeof SaasAppOrgOrganizationSlugSettingsDangerZoneRoute
  SaasAppOrgOrganizationSlugSettingsGeneralRoute: typeof SaasAppOrgOrganizationSlugSettingsGeneralRoute
  SaasAppOrgOrganizationSlugSettingsIntegrationsRoute: typeof SaasAppOrgOrganizationSlugSettingsIntegrationsRoute
  SaasAppOrgOrganizationSlugSettingsMembersRoute: typeof SaasAppOrgOrganizationSlugSettingsMembersRoute
  SaasAppOrgOrganizationSlugSettingsRolesRoute: typeof SaasAppOrgOrganizationSlugSettingsRolesRoute
  SaasAppOrgOrganizationSlugSettingsWebhooksRoute: typeof SaasAppOrgOrganizationSlugSettingsWebhooksRoute
  SaasAppOrgOrganizationSlugSettingsIndexRoute: typeof SaasAppOrgOrganizationSlugSettingsIndexRoute
}

const SaasAppOrgOrganizationSlugSettingsRouteChildren: SaasAppOrgOrganizationSlugSettingsRouteChildren =
  {
    SaasAppOrgOrganizationSlugSettingsApiKeysRoute:
      SaasAppOrgOrganizationSlugSettingsApiKeysRoute,
    SaasAppOrgOrganizationSlugSettingsAuditRoute:
      SaasAppOrgOrganizationSlugSettingsAuditRoute,
    SaasAppOrgOrganizationSlugSettingsBillingRoute:
      SaasAppOrgOrganizationSlugSettingsBillingRoute,
    SaasAppOrgOrganizationSlugSettingsDangerZoneRoute:
      SaasAppOrgOrganizationSlugSettingsDangerZoneRoute,
    SaasAppOrgOrganizationSlugSettingsGeneralRoute:
      SaasAppOrgOrganizationSlugSettingsGeneralRoute,
    SaasAppOrgOrganizationSlugSettingsIntegrationsRoute:
      SaasAppOrgOrganizationSlugSettingsIntegrationsRoute,
    SaasAppOrgOrganizationSlugSettingsMembersRoute:
      SaasAppOrgOrganizationSlugSettingsMembersRoute,
    SaasAppOrgOrganizationSlugSettingsRolesRoute:
      SaasAppOrgOrganizationSlugSettingsRolesRoute,
    SaasAppOrgOrganizationSlugSettingsWebhooksRoute:
      SaasAppOrgOrganizationSlugSettingsWebhooksRoute,
    SaasAppOrgOrganizationSlugSettingsIndexRoute:
      SaasAppOrgOrganizationSlugSettingsIndexRoute,
  }

const SaasAppOrgOrganizationSlugSettingsRouteWithChildren =
  SaasAppOrgOrganizationSlugSettingsRoute._addFileChildren(
    SaasAppOrgOrganizationSlugSettingsRouteChildren,
  )

interface SaasAppOrgOrganizationSlugRouteChildren {
  SaasAppOrgOrganizationSlugSettingsRoute: typeof SaasAppOrgOrganizationSlugSettingsRouteWithChildren
  SaasAppOrgOrganizationSlugIndexRoute: typeof SaasAppOrgOrganizationSlugIndexRoute
}

const SaasAppOrgOrganizationSlugRouteChildren: SaasAppOrgOrganizationSlugRouteChildren =
  {
    SaasAppOrgOrganizationSlugSettingsRoute:
      SaasAppOrgOrganizationSlugSettingsRouteWithChildren,
    SaasAppOrgOrganizationSlugIndexRoute: SaasAppOrgOrganizationSlugIndexRoute,
  }

const SaasAppOrgOrganizationSlugRouteWithChildren =
  SaasAppOrgOrganizationSlugRoute._addFileChildren(
    SaasAppOrgOrganizationSlugRouteChildren,
  )

interface SaasAppRouteChildren {
  SaasAppAccountRoute: typeof SaasAppAccountRouteWithChildren
  SaasAppFullbleedOrganizationSlugRoute: typeof SaasAppFullbleedOrganizationSlugRoute
  SaasAppOrgOrganizationSlugRoute: typeof SaasAppOrgOrganizationSlugRouteWithChildren
}

const SaasAppRouteChildren: SaasAppRouteChildren = {
  SaasAppAccountRoute: SaasAppAccountRouteWithChildren,
  SaasAppFullbleedOrganizationSlugRoute: SaasAppFullbleedOrganizationSlugRoute,
  SaasAppOrgOrganizationSlugRoute: SaasAppOrgOrganizationSlugRouteWithChildren,
}

const SaasAppRouteWithChildren =
  SaasAppRoute._addFileChildren(SaasAppRouteChildren)

interface SaasRouteChildren {
  SaasAppRoute: typeof SaasAppRouteWithChildren
  SaasChoosePlanRoute: typeof SaasChoosePlanRoute
  SaasNewOrganizationRoute: typeof SaasNewOrganizationRoute
  SaasOnboardingRoute: typeof SaasOnboardingRoute
  SaasOrganizationInvitationInvitationIdRoute: typeof SaasOrganizationInvitationInvitationIdRoute
}

const SaasRouteChildren: SaasRouteChildren = {
  SaasAppRoute: SaasAppRouteWithChildren,
  SaasChoosePlanRoute: SaasChoosePlanRoute,
  SaasNewOrganizationRoute: SaasNewOrganizationRoute,
  SaasOnboardingRoute: SaasOnboardingRoute,
  SaasOrganizationInvitationInvitationIdRoute:
    SaasOrganizationInvitationInvitationIdRoute,
}

const SaasRouteWithChildren = SaasRoute._addFileChildren(SaasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  SaasRoute: SaasRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ImageProxySplatRoute: ImageProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
