-- AlterTable
ALTER TABLE "customer" ADD COLUMN     "externalId" TEXT;

-- CreateTable
CREATE TABLE "customer_transaction" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "externalId" TEXT,
    "credit" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "debit" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "notes" TEXT,
    "operationDate" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "customer_transaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_invoice" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "externalId" TEXT,
    "invoiceNumber" TEXT,
    "year" INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    "invoiceDate" TIMESTAMP(3) NOT NULL,
    "expiryDate" TIMESTAMP(3),
    "total" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "discount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "tax" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalWithTax" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "paid" BOOLEAN NOT NULL DEFAULT false,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "customer_invoice_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "customer_transaction_customerId_idx" ON "customer_transaction"("customerId");

-- CreateIndex
CREATE INDEX "customer_transaction_organizationId_idx" ON "customer_transaction"("organizationId");

-- CreateIndex
CREATE INDEX "customer_invoice_customerId_idx" ON "customer_invoice"("customerId");

-- CreateIndex
CREATE INDEX "customer_invoice_organizationId_idx" ON "customer_invoice"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "customer_organizationId_externalId_key" ON "customer"("organizationId", "externalId");

-- AddForeignKey
ALTER TABLE "customer_transaction" ADD CONSTRAINT "customer_transaction_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_transaction" ADD CONSTRAINT "customer_transaction_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_invoice" ADD CONSTRAINT "customer_invoice_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_invoice" ADD CONSTRAINT "customer_invoice_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
