-- This migration was auto-generated by Prisma because the GIN index
-- isn't tracked in the schema (Unsupported type). We recreate it here
-- to ensure it exists for full-text search.

-- Ensure GIN index exists for tsvector search
CREATE INDEX IF NOT EXISTS "chatbot_document_search_vector_idx"
ON "chatbot_document" USING GIN ("searchVector");
