-- DropIndex
DROP INDEX "customer_organizationId_fullName_idx";

-- AlterTable
ALTER TABLE "access_point" ADD COLUMN     "autoNegotiation" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "fullDuplex" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scanStatus" TEXT;

-- AlterTable
ALTER TABLE "customer" ADD COLUMN     "addedHours" INTEGER,
ADD COLUMN     "apElectrical" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoGenerateInvoice" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "canResetAccount" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "canShowTrafficDetails" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "collectorCanShowLinks" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "collectorResetMac" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "conditionAccountTypeId" INTEGER,
ADD COLUMN     "deductMoney" DOUBLE PRECISION,
ADD COLUMN     "excludeDailyDownloadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "excludeDailyUploadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "excludeFreeDailyDownloadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "excludeFreeDailyUploadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "excludeFreeMonthlyDownloadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "excludeFreeMonthlyUploadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "excludeMonthlyDownloadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "excludeMonthlyUploadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "extraDaysToAddOnRefill" INTEGER,
ADD COLUMN     "extraDaysToDeductOnRefill" INTEGER,
ADD COLUMN     "extraDownloadGb" DOUBLE PRECISION,
ADD COLUMN     "extraUploadGb" DOUBLE PRECISION,
ADD COLUMN     "financialCategoryId" INTEGER,
ADD COLUMN     "firstName" TEXT,
ADD COLUMN     "forceAutoBindAccToMac" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "forceExpiryAfterDays" INTEGER,
ADD COLUMN     "forceOverrideImmediateRecharge" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "forwardAccountTypeId" INTEGER,
ADD COLUMN     "freeDailyDownloadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "freeDailyUploadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "freeDownloadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "freeUploadBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "lastLogOut" TIMESTAMP(3),
ADD COLUMN     "lastLogin" TIMESTAMP(3),
ADD COLUMN     "lastName" TEXT,
ADD COLUMN     "linkId" INTEGER,
ADD COLUMN     "mikrotikInterface1" TEXT,
ADD COLUMN     "mikrotikQueue" TEXT,
ADD COLUMN     "mobile" TEXT,
ADD COLUMN     "mof" TEXT,
ADD COLUMN     "nasAccountId" INTEGER,
ADD COLUMN     "nasLastLogOut" TIMESTAMP(3),
ADD COLUMN     "oldAccountTypeId" INTEGER,
ADD COLUMN     "overrideAutoBindAccToMac" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "overrideExpiryAccount" TIMESTAMP(3),
ADD COLUMN     "overrideImmediateRecharge" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reachMaxQuota" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "readOnly" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "routerBrandPrefix" TEXT,
ADD COLUMN     "simultaneous" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tempExpiryAccount" TIMESTAMP(3),
ADD COLUMN     "tempUser" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "wirelessInterface" TEXT,
ALTER COLUMN "fullName" DROP NOT NULL;

-- AlterTable
ALTER TABLE "customer_invoice" ADD COLUMN     "blocked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "generatedDate" TIMESTAMP(3),
ADD COLUMN     "vatValue" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "isp_dealer" ADD COLUMN     "canMonitorLog" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "canShowOnlineUsersSpeed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "chargeIfNotExpiry" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "extraGb" DOUBLE PRECISION,
ADD COLUMN     "notifyBefore1Day" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notifyBefore2Days" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notifyBefore3Days" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "userNotification" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "isp_nas" ADD COLUMN     "adminId" INTEGER,
ADD COLUMN     "apiPassword" TEXT,
ADD COLUMN     "apiUserName" TEXT,
ADD COLUMN     "countFaultSession" INTEGER,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "faultSession" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "mikrotikNewVersion" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "minutesToRemoveNasFilter" INTEGER,
ADD COLUMN     "nasTypeId" INTEGER,
ADD COLUMN     "onlineUsers" INTEGER,
ADD COLUMN     "sshPassword" TEXT,
ADD COLUMN     "sshPort" INTEGER,
ADD COLUMN     "sshUserName" TEXT;

-- AlterTable
ALTER TABLE "service_plan" ADD COLUMN     "accountTypeCategory" INTEGER,
ADD COLUMN     "addressListId" INTEGER,
ADD COLUMN     "adminId" INTEGER,
ADD COLUMN     "autoBindAccToMac" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "canChangeMac" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "canChangeUserName" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "canExcludeQuotaByIpAddress" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "combinedMaxUpAndDown" INTEGER,
ADD COLUMN     "defaultAddressListIds" INTEGER,
ADD COLUMN     "disablePoolName" TEXT,
ADD COLUMN     "expiryAccountPool" TEXT,
ADD COLUMN     "expiryProceraId" INTEGER,
ADD COLUMN     "fupResetPrice" DOUBLE PRECISION,
ADD COLUMN     "iRadiusNasId" INTEGER,
ADD COLUMN     "immediateRecharge" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "monthlyPoolAfterMax" TEXT,
ADD COLUMN     "newIpPoolAfterMax" TEXT,
ADD COLUMN     "preventBeforeRecharge" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "proceraId" INTEGER,
ADD COLUMN     "queueTreeMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "rate" DOUBLE PRECISION,
ADD COLUMN     "refundable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "refundableByGb" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "resetCounterTime" TEXT,
ADD COLUMN     "sellingPrice" DOUBLE PRECISION,
ADD COLUMN     "separateMaxMonthlyDown" INTEGER,
ADD COLUMN     "separateMaxMonthlyUp" INTEGER,
ADD COLUMN     "totalSession" INTEGER,
ADD COLUMN     "totalSessionPeriodTypeId" INTEGER,
ADD COLUMN     "ulDlForAutoFallBack" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "ulDlMonthlyForAutoFallBack" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "unlimitedTimeFrom" TEXT,
ADD COLUMN     "unlimitedTimeTo" TEXT,
ADD COLUMN     "validityPeriodTypeId" INTEGER;

-- AlterTable
ALTER TABLE "station" ADD COLUMN     "apApiPort" INTEGER,
ADD COLUMN     "apSshPort" INTEGER,
ADD COLUMN     "boardName" TEXT,
ADD COLUMN     "cpuLoad" TEXT,
ADD COLUMN     "online" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scanStatus" TEXT,
ADD COLUMN     "voltage" TEXT;

-- CreateIndex
CREATE INDEX "customer_organizationId_lastName_firstName_idx" ON "customer"("organizationId", "lastName", "firstName");
