-- Decouple invoice/transaction data from iRadius.
--
-- 1. Drop the historical iRadius-synced invoice data — local generation
--    (see packages/api/modules/billing/lib/generate-invoices.ts) takes over
--    from the current billing month forward. Done BEFORE the unique index
--    is added so duplicates from iRadius sync can't break the upgrade.
-- 2. Collapse any remaining duplicate (org, customer, year, month) rows,
--    keeping the most recent by createdAt.
-- 3. Drop iRadius-only columns and the customer_transaction table.
-- 4. Add the natural unique key that local generation upserts on.

-- ── Data cleanup (runs before schema changes) ──────────────────────────

-- Drop all invoice rows — local generation re-creates from the current
-- billing month onward, and collectors operate on Payment rows anyway.
DELETE FROM "customer_invoice";

-- Safety dedup in case any stray duplicates survive (no-op after the
-- DELETE above, but cheap insurance and makes the migration replayable).
DELETE FROM "customer_invoice" a
USING "customer_invoice" b
WHERE a."organizationId" = b."organizationId"
  AND a."customerId"     = b."customerId"
  AND a.year             = b.year
  AND a.month            = b.month
  AND a."createdAt"      < b."createdAt";

-- customer_transaction is dropped entirely; the transactions tab now
-- derives from Payment + CustomerInvoice in list-transactions.ts.

-- ── Schema changes ────────────────────────────────────────────────────

-- DropForeignKey
ALTER TABLE "customer_transaction" DROP CONSTRAINT "customer_transaction_collectorId_fkey";
ALTER TABLE "customer_transaction" DROP CONSTRAINT "customer_transaction_customerId_fkey";
ALTER TABLE "customer_transaction" DROP CONSTRAINT "customer_transaction_organizationId_fkey";

-- DropIndex
DROP INDEX "customer_invoice_organizationId_externalId_key";

-- AlterTable
ALTER TABLE "customer_invoice"
  DROP COLUMN "autoGenerated",
  DROP COLUMN "blocked",
  DROP COLUMN "externalId",
  DROP COLUMN "generatedDate",
  DROP COLUMN "invoiceNumber",
  DROP COLUMN "lastSyncedAt",
  DROP COLUMN "vatValue";

-- AlterTable
ALTER TABLE "iradius_sync_operation"
  DROP COLUMN "processedInvoices",
  DROP COLUMN "processedTransactions",
  DROP COLUMN "totalInvoices",
  DROP COLUMN "totalTransactions";

-- DropTable
DROP TABLE "customer_transaction";

-- CreateIndex
CREATE UNIQUE INDEX "customer_invoice_organizationId_customerId_year_month_key"
  ON "customer_invoice" ("organizationId", "customerId", "year", "month");
